GuessingApp/GuessApp/urls.py
from django.urls import path
from . import views

app_name = "GuessApp"

urlpatterns = [
    path("", views.indexView.as_view(), name="index"),
]

GuessingApp/GuessingApp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("GuessApp.urls"))
]

GuessingApp/GuessApp/models.py
from django.db import models

# Create your models here.

GuessingApp/GuessApp/views.py
from django.shortcuts import render
from django.views import View
from django.shortcuts import redirect
import random

# Create your views here.

def randomNum():
    global correctGuess
    correctGuess = random.randint(0,100)
randomNum()

previousGuesses = []

def checkguess(guess):
    guess = int(guess)
    if guess > correctGuess:
        return "Guess was too large"
    elif guess < correctGuess:
        return "Guess was too small"
    elif guess == correctGuess:
        return "Correct guess!"

class indexView(View):
    def get(self, request):
        msg = request.session.get('msg', False)
        if (msg) : del(request.session['msg']) 
        return render(request, 'GuessApp/index.html', {'message': msg,
                                                       'guesses': reversed(previousGuesses)})

    def post(self, request):
        if request.POST.get("again"):
            randomNum()
            previousGuesses.clear()
            return redirect(request.path)

        guess = request.POST.get("guess")
        msg = checkguess(guess)
        request.session['msg'] = msg
        previousGuesses.append(guess)
        return redirect(request.path)

GuessingApp/GuessApp/templates/GuessApp/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>Guessing Game</title>
    </head>
    <body>
        <h1>Guess the number</h1>
        {% if message %}
            {{ message }}
        {% endif %}
        <form action="{% url 'GuessApp:index' %}" method="post">
            {% csrf_token %}
            <input type="number" name="guess" autofocus >
            <input type="submit" value="Guess">
            <input type="submit" name="again" value="Play Again">
        </form>
        <h3>Previous Guesses</h3>
        <ol reversed >
            {% for guess in guesses %}
                <li>{{ guess }}</li>
            {% empty %}
                No guesses
            {% endfor %}
        </ol>
    </body>
</html>